data_config:
  
  dataset_path: "/mnt/rhome/sharedgroup_ijr/speedplus2/" # Path to your dataset
  keypoints_path: "assets/keypoints.json" # Path to the keypoint file

  target_size: [192, 256] # Input image size

  filter_points: true # Flag to filter keypoints that are 
  filter_margin: 2    # filter_marging pixels close to the border

  in_channels: 1      # Input image channels
  num_keypoints: 11   # Number of total keypoints


training_config:

  device: "cuda:0"
  num_workers: 8
  batch_size: 186
  num_epochs: 20  
  learning_rate: 2.5e-4
  betas: [0.9, 0.99]
  weight_decay: 0
  weight_decay: 0
  layer_decay_rate: 0.75
  num_layers: 12
  step: [170, 200]
  gamma: 0.1
  warmup_iters: 500
  warmup_ratio: 0.001
  w_heatmap: 1.0

  augmentation_geometric: True
  augmentation_intensity: True
  normalize_minmax: True

backbone_config:

  backbone: "resnet"
  resnet_size: 18 # if resnet

  # if vit
  patch_size: 16
  depth: 12
  num_heads: 12
  ratio: 1
  use_checkpoint: false
  mlp_ratio: 4
  qkv_bias: true
  drop_path_rate: 0.3

  embed_dim: 512 



head_config:
  fixed_std: false
  std_val: 7  # if std is fixed, what is the value of the 
  scale_std: 1
  num_deconv_layers: 5
  num_deconv_filters: [128, 128, 128, 128, 128]
  num_deconv_kernels: [4, 4, 4, 4, 4]


logging_config:

  log_interval: 10
  save_val_examples: true
  val_examples_interval: 10
  examples_path: "outputs/val_examples/"
