data_config:
  
  dataset_path: "/home/jbp/Downloads/SwissCube_1.0/" # Path to your dataset
  keypoints_path: "assets/keypoints.json" # Path to the keypoint file

  target_size: [384, 384] # Input image size

  filter_points: true # Flag to filter keypoints that are 
  filter_margin: 2    # filter_marging pixels close to the border

  im_channels: 3      # Input image channels
  num_keypoints: 8   # Number of total keypoints

  dataset: "swisscube"

training_config:

  device: "cuda:0"
  num_workers: 8
  batch_size: 78
  num_epochs: 200  
  learning_rate: 0.00005
  lr_factor : 0.1
  betas: [0.9,  0.99]
  weight_decay: 0.000001

  lr_step: [190, 195]


  w_heatmap: 10000

  augmentation_geometric: True
  augmentation_intensity: False
  normalize_minmax: False

backbone_config:

  backbone: "resnet"
  resnet_size: 18 # if resnet

head_config:

  fixed_std: True
  std_val: 7.0  # if std is fixed, what is the value of the 
  scale_std: 1.0
  num_deconv_layers: 5
  num_deconv_filters: [128, 128, 128, 128, 128]
  num_deconv_kernels: [4, 4, 4, 4, 4]


logging_config:

  log_interval: 10
  save_val_examples: true
  val_examples_interval: 10
  examples_path: "outputs/val_examples/"
